export interface SectionData {
  id: number;
  name: string;
  shortName: string;
  category: string;
  statistic: string;
  img: string;
  shadowColor: string;
  resourceIds: number[];
}
export const sectionData: SectionData[] = [
  {
    id: 1,
    name: "Агропромышленный комплекс",
    shortName: "АПК",
    category: "Сельское хозяйство",
    statistic: "124 объекта",
    img: "/apk.svg",
    shadowColor: "#7CB34240",
    resourceIds: [262, 522],
  },
  {
    id: 2,
    name: "Ресурсы",
    shortName: "Ресурсы",
    category: "Природные ресурсы",
    statistic: "89 слоёв",
    img: "/resources.svg",
    shadowColor: "#8D6E6340",
    resourceIds: [226],
  },
  {
    id: 3,
    name: "Образование и спорт",
    shortName: "Соц",
    category: "Инфраструктура",
    statistic: "312 учреждений",
    img: "/social.svg",
    shadowColor: "#42A5F540",
    resourceIds: [254],
  },
  {
    id: 4,
    name: "Экология",
    shortName: "Эко",
    category: "Мониторинг среды",
    statistic: "47 постов",
    img: "/eco.svg",
    shadowColor: "#26A69A40",
    resourceIds: [531, 532, 579, 520, 1117],
  },
  {
    id: 5,
    name: "Транспорт",
    shortName: "Транс",
    category: "Транспортная инфраструктура",
    statistic: "1 284 объекта",
    img: "/bus.svg",
    shadowColor: "#78909C40",
    resourceIds: [714],
  },
  {
    id: 6,
    name: "Культура",
    shortName: "Культура",
    category: "Культура и туризм",
    statistic: "76 объектов",
    img: "/culture.svg",
    shadowColor: "#AB47BC40",
    resourceIds: [384, 389, 1024],
  },
  {
    id: 7,
    name: "Гектар в Арктике",
    shortName: "Арктика",
    category: "Земельные участки",
    statistic: "2 388 участков",
    img: "/arctica.svg",
    shadowColor: "#4DD0E140",
    resourceIds: [498],
  },
  {
    id: 8,
    name: "Данные ДЗЗ",
    shortName: "ДЗЗ",
    category: "Дистанционное зондирование",
    statistic: "5.2 ТБ данных",
    img: "/dzz.svg",
    shadowColor: "#5C6BC040",
    resourceIds: [466],
  },
  {
    id: 9,
    name: "Информатизация и связь",
    shortName: "ИТ",
    category: "Цифровая инфраструктура",
    statistic: "18 узлов",
    img: "/it.svg",
    shadowColor: "#29B6F640",
    resourceIds: [1049],
  },
  {
    id: 10,
    name: "Здравоохранение",
    shortName: "Мед",
    category: "Медицинские объекты",
    statistic: "63 учреждения",
    img: "/med.svg",
    shadowColor: "#EF535040",
    resourceIds: [1041],
  },
  {
    id: 11,
    name: "Строительство",
    shortName: "Строй",
    category: "Градостроительство",
    statistic: "34 площадки",
    img: "/build.svg",
    shadowColor: "#FFA72640",
    resourceIds: [1054],
  },
  {
    id: 12,
    name: "Муниципальные образования",
    shortName: "МО",
    category: "Территории и муниципалитеты",
    statistic: "28 служб",
    img: "/mo.svg",
    shadowColor: "#D4E15740",
    resourceIds: [966],
  },
];
