import { CardProps } from "@/app/main/components/Card";

export interface SectionData extends CardProps {
  resourceIds: number[];
}

export const sectionData: SectionData[] = [
  {
    name: "Агропромышленный комплекс",
    shortName: "АПК",
    category: "Сельское хозяйство",
    statistic: "124 объекта",
    img: "/apk.svg",
    shadowColor: "#7CB34240",
    resourceIds: [262, 480],
  },
  {
    name: "Ресурсы",
    shortName: "Ресурсы",
    category: "Природные ресурсы",
    statistic: "89 слоёв",
    img: "/resources.svg",
    shadowColor: "#8D6E6340",
    resourceIds: [484],
  },
  {
    name: "Образование и спорт",
    shortName: "Соц",
    category: "Инфраструктура",
    statistic: "312 учреждений",
    img: "/social.svg",
    shadowColor: "#42A5F540",
    resourceIds: [254],
  },
  {
    name: "Экология",
    shortName: "Эко",
    category: "Мониторинг среды",
    statistic: "47 постов",
    img: "/eco.svg",
    shadowColor: "#26A69A40",
    resourceIds: [490, 506, 488, 725],
  },
  {
    name: "Реестр жилищного фонда",
    shortName: "ЖКХ",
    category: "Непригодное жильё",
    statistic: "1 284 объекта",
    img: "/zhkh.svg",
    shadowColor: "#78909C40",
    resourceIds: [614],
  },
  {
    name: "Культура",
    shortName: "Культура",
    category: "Культура и туризм",
    statistic: "76 объектов",
    img: "/culture.svg",
    shadowColor: "#AB47BC40",
    resourceIds: [384, 389],
  },
  {
    name: "Гектар в Арктике",
    shortName: "Арктика",
    category: "Земельные участки",
    statistic: "2 388 участков",
    img: "/arctica.svg",
    shadowColor: "#4DD0E140",
    resourceIds: [476],
  },
  {
    name: "Данные ДЗЗ",
    shortName: "ДЗЗ",
    category: "Дистанционное зондирование",
    statistic: "5.2 ТБ данных",
    img: "/dzz.svg",
    shadowColor: "#5C6BC040",
    resourceIds: [470],
  },
  {
    name: "Информатизация и связь",
    shortName: "ИТ",
    category: "Цифровая инфраструктура",
    statistic: "18 узлов",
    img: "/it.svg",
    shadowColor: "#29B6F640",
    resourceIds: [649, 701],
  },
  {
    name: "Здравоохранение",
    shortName: "Мед",
    category: "Медицинские объекты",
    statistic: "63 учреждения",
    img: "/med.svg",
    shadowColor: "#EF535040",
    resourceIds: [695],
  },
  {
    name: "Инвестиции",
    shortName: "Бизнес",
    category: "Инвестиционные площадки",
    statistic: "34 площадки",
    img: "/business.svg",
    shadowColor: "#FFA72640",
    resourceIds: [536],
  },
  {
    name: "Гражданская защита",
    shortName: "ЧС",
    category: "ЧС и безопасность",
    statistic: "28 служб",
    img: "/chs.svg",
    shadowColor: "#D4E15740",
    resourceIds: [497,557],
  },
];
