import { CardProps } from "@/components/Card";
export const sectionData: CardProps[] = [
  {
    name: "Агропромышленный комплекс",
    shortName: "АПК",
    category: "Сельское хозяйство",
    statistic: "124 объекта",
    img: "apk.svg",
    link: "map/apk",
    shadowColor: "#7CB34240",
  },
  {
    name: "Ресурсы",
    shortName: "Ресурсы",
    category: "Природные ресурсы",
    statistic: "89 слоёв",
    img: "resources.svg",
    link: "map/resources",
    shadowColor: "#8D6E6340",
  },
  {
    name: "Образование и спорт",
    shortName: "Соц",
    category: "Инфраструктура",
    statistic: "312 учреждений",
    img: "social.svg",
    link: "map/social",
    shadowColor: "#42A5F540",
  },
  {
    name: "Экология",
    shortName: "Эко",
    category: "Мониторинг среды",
    statistic: "47 постов",
    img: "eco.svg",
    link: "map/eco",
    shadowColor: "#26A69A40",
  },
  {
    name: "Реестр жилищного фонда",
    shortName: "ЖКХ",
    category: "Непригодное жильё",
    statistic: "1 284 объекта",
    img: "zhkh.svg",
    link: "map/zhkh",
    shadowColor: "#78909C40",
  },
  {
    name: "Культура",
    shortName: "Культура",
    category: "Культура и туризм",
    statistic: "76 объектов",
    img: "culture.svg",
    link: "map/culture",
    shadowColor: "#AB47BC40",
  },
  {
    name: "Гектар в Арктике",
    shortName: "Арктика",
    category: "Земельные участки",
    statistic: "2 388 участков",
    img: "arctica.svg",
    link: "map/arctica",
    shadowColor: "#4DD0E140",
  },
  {
    name: "Данные ДЗЗ",
    shortName: "ДЗЗ",
    category: "Дистанционное зондирование",
    statistic: "5.2 ТБ данных",
    img: "dzz.svg",
    link: "map/dzz",
    shadowColor: "#5C6BC040",
  },
  {
    name: "Информатизация и связь",
    shortName: "ИТ",
    category: "Цифровая инфраструктура",
    statistic: "18 узлов",
    img: "it.svg",
    link: "map/it",
    shadowColor: "#29B6F640",
  },
  {
    name: "Здравоохранение",
    shortName: "Мед",
    category: "Медицинские объекты",
    statistic: "63 учреждения",
    img: "med.svg",
    link: "map/med",
    shadowColor: "#EF535040",
  },
  {
    name: "Инвестиции",
    shortName: "Бизнес",
    category: "Инвестиционные площадки",
    statistic: "34 площадки",
    img: "business.svg",
    link: "map/business",
    shadowColor: "#FFA72640",
  },
  {
    name: "Гражданская защита",
    shortName: "ЧС",
    category: "ЧС и безопасность",
    statistic: "28 служб",
    img: "chs.svg",
    link: "map/chs",
    shadowColor: "#D4E15740",
  },
];